In [1]:
import pandas as pd
df = pd.DataFrame([1,2 ,3])

In [2]:
print(df)

   0
0  1
1  2
2  3


In [3]:
for x in df:
    print(x)

0


In [1]:
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix
y_true = np.array([[1, 0, 1, 0, 0],
                   [0, 1, 0, 1, 1],
                   [1, 1, 1, 0, 1]])
y_pred = np.array([[1, 0, 0, 0, 1],
                   [0, 1, 1, 1, 0],
                   [1, 1, 1, 0, 0]])

In [2]:
mcm = multilabel_confusion_matrix(y_true, y_pred)

In [4]:
print(mcm)

[[[1 0]
  [0 2]]

 [[1 0]
  [0 2]]

 [[0 1]
  [1 1]]

 [[2 0]
  [0 1]]

 [[0 1]
  [2 0]]]


In [17]:
from sklearn.metrics import classification_report
cr = classification_report(y_true, y_pred)

In [18]:
print(type(cr))
print(cr)

<class 'str'>
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2
           2       0.50      0.50      0.50         2
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         2

   micro avg       0.75      0.67      0.71         9
   macro avg       0.70      0.70      0.70         9
weighted avg       0.67      0.67      0.67         9
 samples avg       0.72      0.64      0.67         9



In [16]:
print(type(cr['macro avg']['f1-score']))

<class 'float'>


In [22]:
import numpy as np
x = np.array([[0.1, 0.6], [0.7, 0.4]])
print(x)
x[x >= 0.5] = 1
x[x <0.5]=0
print(x)

[[0.1 0.6]
 [0.7 0.4]]
[[0. 1.]
 [1. 0.]]


In [18]:
import pickle
with open('./usual_k_fold_model/BertLabelSmooth/oof_train','rb') as f:
    data_train = pickle.load(f)

In [19]:
data_train[0]

array([0.83446109, 0.03880742, 0.03337306, 0.21564159, 0.0335976 ,
       0.14355932, 0.07865674, 0.0170052 ])

In [20]:
print('*'*10)

**********


In [21]:
len(data_train)

26000

In [22]:
import torch
import torch.nn as nn
sigmoid_layer = nn.Sigmoid()
x = torch.Tensor([[1, -10, 100], [-1000, 200, 300]])
y = sigmoid_layer(x)
print(x)
print(y)
y[y>=0.5]=1
y[y<0.5]=0
print(y)

tensor([[    1.,   -10.,   100.],
        [-1000.,   200.,   300.]])
tensor([[7.3106e-01, 4.5398e-05, 1.0000e+00],
        [0.0000e+00, 1.0000e+00, 1.0000e+00]])
tensor([[1., 0., 1.],
        [0., 1., 1.]])
